### PR TITLE
Pass correct variable

### LINKED ISSUE #2: Incorrect Syntax on upload error
When a file upload error occurs, we are trying to emit 'response' to the parent, but response is undefined this should be 'errorMessage'

https://github.com/CroudTech/vue-dropzone/blob/ea804d1e227184aac432843c587b2d88c429fc48/src/Dropzone.vue#L157

### PR DESCRIPTION
**Pull request by kingy04**
fixes #2, emits the correct errorMessage variable

### CODE REVIEW

File: src/Dropzone.vue [hunk 1]
```diff
@@ -154,7 +154,7 @@ export default {
                 this.$emit('uploading', false);
                 this.$emit('file-upload-error', {
                     file: file,
-                    response: response,
+                    errorMessage: errorMessage,
```
Comment (BrockReece) [inline src/Dropzone.vue]: We have changed key names here, is this going to introduce any breaking changes for code expecting the old `response` key?

Comment (kingy04) [reply src/Dropzone.vue]: Thats a good point @BrockReece, i guess it makes sense to keep the key name the same. Thanks

**Review by BrockReece — APPROVED** [review]

**Comment by BrockReece** [comment]
Released in v1.0.2
